### ISSUE TITLE
Dockerfile not working 

### ISSUE THREAD

**Issue by cyniu88** [oysteing/comfoconnect-mqtt-bridge#2]
I can not build docker image because of this: 

pi@iDom-RaspberryPi4:~/GIT/comfoconnect-mqtt-bridge $ docker build . -t comfoconnect-mqtt-bridge
Sending build context to Docker daemon  98.82kB
Step 1/6 : FROM python:slim
 ---> 50e61686af4c
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> f55bb3bf27c8
Step 3/6 : COPY requirements.txt .
 ---> 7a8c3c43cdd1
Step 4/6 : RUN pip install -r requirements.txt
 ---> Running in 0b2061ba4af9
Collecting aiocomfoconnect==0.1.5 (from -r requirements.txt (line 1))
  Downloading aiocomfoconnect-0.1.5-py3-none-any.whl (28 kB)
Collecting aiohttp==3.8.4 (from -r requirements.txt (line 2))
  Downloading aiohttp-3.8.4.tar.gz (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 9.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting aiomqtt==1.0.0 (from -r requirements.txt (line 3))
  Obtaining dependency information for aiomqtt==1.0.0 from https://files.pythonhosted.org/packages/cf/7b/c842643452c12c02a1cbc03c9cef24188c81d7b557bd319ebd2c065dbf75/aiomqtt-1.0.0-py3-none-any.whl.metadata
  Downloading aiomqtt-1.0.0-py3-none-any.whl.metadata (8.4 kB)
Collecting aiosignal==1.3.1 (from -r requirements.txt (line 4))
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout==4.0.2 (from -r requirements.txt (line 5))
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs==23.1.0 (from -r requirements.txt (line 6))
  Downloading attrs-23.1.0-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 3.3 MB/s eta 0:00:00
Collecting build==0.10.0 (from -r requirements.txt (line 7))
  Downloading build-0.10.0-py3-none-any.whl (17 kB)
Collecting charset-normalizer==3.1.0 (from -r requirements.txt (line 8))
  Downloading charset_normalizer-3.1.0-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 kB 2.7 MB/s eta 0:00:00
Collecting frozenlist==1.3.3 (from -r requirements.txt (line 9))
  Downloading frozenlist-1.3.3.tar.gz (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.6/66.6 kB 3.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting idna==3.4 (from -r requirements.txt (line 10))
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 3.2 MB/s eta 0:00:00
Collecting multidict==6.0.4 (from -r requirements.txt (line 11))
  Downloading multidict-6.0.4.tar.gz (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 2.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting nanopb==0.4.7 (from -r requirements.txt (line 12))
  Downloading nanopb-0.4.7-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 2.7 MB/s eta 0:00:00
Collecting packaging==23.1 (from -r requirements.txt (line 13))
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 2.5 MB/s eta 0:00:00
Collecting paho-mqtt==1.6.1 (from -r requirements.txt (line 14))
  Downloading paho-mqtt-1.6.1.tar.gz (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.4/99.4 kB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting protobuf==4.23.3 (from -r requirements.txt (line 15))
  Obtaining dependency information for protobuf==4.23.3 from https://files.pythonhosted.org/packages/90/ca/da1d7e066196c8da33600bc74a31bb5b5e5538d00977e9fba4eb106992e9/protobuf-4.23.3-cp37-abi3-manylinux2014_aarch64.whl.metadata
  Downloading protobuf-4.23.3-cp37-abi3-manylinux2014_aarch64.whl.metadata (540 bytes)
Collecting pyproject_hooks==1.0.0 (from -r requirements.txt (line 16))
  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Collecting tomli==2.0.1 (from -r requirements.txt (line 17))
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting yarl==1.9.2 (from -r requirements.txt (line 18))
  Downloading yarl-1.9.2.tar.gz (184 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.7/184.7 kB 6.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Downloading aiomqtt-1.0.0-py3-none-any.whl (14 kB)
Downloading protobuf-4.23.3-cp37-abi3-manylinux2014_aarch64.whl (303 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.5/303.5 kB 4.6 MB/s eta 0:00:00
Building wheels for collected packages: aiohttp, frozenlist, multidict, paho-mqtt, yarl
  Building wheel for aiohttp (pyproject.toml): started
  Building wheel for aiohttp (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for aiohttp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [97 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      creating build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/base_protocol.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/streams.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/__init__.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_request.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/client_proto.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/payload_streamer.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/cookiejar.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/test_utils.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/locks.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/worker.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/http_exceptions.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/connector.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/multipart.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/log.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/abc.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/client_reqrep.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_fileresponse.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_exceptions.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_middlewares.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/resolver.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_urldispatcher.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_runner.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_log.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/tracing.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_routedef.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/http_parser.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/http.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_ws.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/http_websocket.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/client_exceptions.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/client_ws.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/client.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_server.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/formdata.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/pytest_plugin.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/typedefs.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/http_writer.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_protocol.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/helpers.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/payload.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/tcp_helpers.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_response.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/hdrs.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/web_app.py -> build/lib.linux-aarch64-cpython-312/aiohttp
      running egg_info
      writing aiohttp.egg-info/PKG-INFO
      writing dependency_links to aiohttp.egg-info/dependency_links.txt
      writing requirements to aiohttp.egg-info/requires.txt
      writing top-level names to aiohttp.egg-info/top_level.txt
      reading manifest file 'aiohttp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'aiohttp' anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching '*.dll' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.obj' found anywhere in distribution
      warning: no previously-included files found matching 'aiohttp/*.html'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE.txt'
      writing manifest file 'aiohttp.egg-info/SOURCES.txt'
      copying aiohttp/_cparser.pxd -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/_find_header.pxd -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/_headers.pxi -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/_helpers.pyi -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/_helpers.pyx -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/_http_parser.pyx -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/_http_writer.pyx -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/_websocket.pyx -> build/lib.linux-aarch64-cpython-312/aiohttp
      copying aiohttp/py.typed -> build/lib.linux-aarch64-cpython-312/aiohttp
      creating build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/_cparser.pxd.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/_find_header.pxd.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyi.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/_helpers.pyx.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/_http_parser.pyx.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/_http_writer.pyx.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/_websocket.pyx.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      copying aiohttp/.hash/hdrs.py.hash -> build/lib.linux-aarch64-cpython-312/aiohttp/.hash
      running build_ext
      building 'aiohttp._websocket' extension
      creating build/temp.linux-aarch64-cpython-312
      creating build/temp.linux-aarch64-cpython-312/aiohttp
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/usr/local/include/python3.12 -c aiohttp/_websocket.c -o build/temp.linux-aarch64-cpython-312/aiohttp/_websocket.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
  Building wheel for frozenlist (pyproject.toml): started
  Building wheel for frozenlist (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for frozenlist (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      creating build/lib.linux-aarch64-cpython-312/frozenlist
      copying frozenlist/__init__.py -> build/lib.linux-aarch64-cpython-312/frozenlist
      running egg_info
      writing frozenlist.egg-info/PKG-INFO
      writing dependency_links to frozenlist.egg-info/dependency_links.txt
      writing top-level names to frozenlist.egg-info/top_level.txt
      reading manifest file 'frozenlist.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.pyd' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      warning: no previously-included files matching '*.lib' found anywhere in distribution
      warning: no previously-included files matching '*.dll' found anywhere in distribution
      warning: no previously-included files matching '*.a' found anywhere in distribution
      warning: no previously-included files matching '*.obj' found anywhere in distribution
      warning: no previously-included files found matching 'frozenlist/*.html'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE'
      writing manifest file 'frozenlist.egg-info/SOURCES.txt'
      copying frozenlist/__init__.pyi -> build/lib.linux-aarch64-cpython-312/frozenlist
      copying frozenlist/_frozenlist.pyx -> build/lib.linux-aarch64-cpython-312/frozenlist
      copying frozenlist/py.typed -> build/lib.linux-aarch64-cpython-312/frozenlist
      running build_ext
      building 'frozenlist._frozenlist' extension
      creating build/temp.linux-aarch64-cpython-312
      creating build/temp.linux-aarch64-cpython-312/frozenlist
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/usr/local/include/python3.12 -c frozenlist/_frozenlist.c -o build/temp.linux-aarch64-cpython-312/frozenlist/_frozenlist.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frozenlist
  Building wheel for multidict (pyproject.toml): started
  Building wheel for multidict (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for multidict (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      *********************
      * Accelerated build *
      *********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      creating build/lib.linux-aarch64-cpython-312/multidict
      copying multidict/__init__.py -> build/lib.linux-aarch64-cpython-312/multidict
      copying multidict/_multidict_base.py -> build/lib.linux-aarch64-cpython-312/multidict
      copying multidict/_abc.py -> build/lib.linux-aarch64-cpython-312/multidict
      copying multidict/_multidict_py.py -> build/lib.linux-aarch64-cpython-312/multidict
      copying multidict/_compat.py -> build/lib.linux-aarch64-cpython-312/multidict
      running egg_info
      writing multidict.egg-info/PKG-INFO
      writing dependency_links to multidict.egg-info/dependency_links.txt
      writing top-level names to multidict.egg-info/top_level.txt
      reading manifest file 'multidict.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files found matching 'multidict/_multidict.html'
      warning: no previously-included files found matching 'multidict/*.so'
      warning: no previously-included files found matching 'multidict/*.pyd'
      warning: no previously-included files found matching 'multidict/*.pyd'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE'
      writing manifest file 'multidict.egg-info/SOURCES.txt'
      /tmp/pip-build-env-4dascdzx/overlay/lib/python3.12/site-packages/setuptools/command/build_py.py:207: _Warning: Package 'multidict._multilib' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'multidict._multilib' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'multidict._multilib' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'multidict._multilib' to be distributed and are
              already explicitly excluding 'multidict._multilib' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      copying multidict/__init__.pyi -> build/lib.linux-aarch64-cpython-312/multidict
      copying multidict/py.typed -> build/lib.linux-aarch64-cpython-312/multidict
      running build_ext
      building 'multidict._multidict' extension
      creating build/temp.linux-aarch64-cpython-312
      creating build/temp.linux-aarch64-cpython-312/multidict
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/usr/local/include/python3.12 -c multidict/_multidict.c -o build/temp.linux-aarch64-cpython-312/multidict/_multidict.o -O2 -std=c99 -Wall -Wsign-compare -Wconversion -fno-strict-aliasing -pedantic
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
  Building wheel for paho-mqtt (setup.py): started
  Building wheel for paho-mqtt (setup.py): finished with status 'done'
  Created wheel for paho-mqtt: filename=paho_mqtt-1.6.1-py3-none-any.whl size=62120 sha256=da540b5afb9240c00b2beb1c25f855c93bf36e02f6c4be24460ae8ec9b01d995
  Stored in directory: /root/.cache/pip/wheels/23/d5/af/1f3cbcc350dec9d8e95040f388e0163d132eff0c9a453db659
  Building wheel for yarl (pyproject.toml): started
  Building wheel for yarl (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for yarl (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      **********************
      * Accelerated build *
      **********************
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      creating build/lib.linux-aarch64-cpython-312/yarl
      copying yarl/__init__.py -> build/lib.linux-aarch64-cpython-312/yarl
      copying yarl/_url.py -> build/lib.linux-aarch64-cpython-312/yarl
      copying yarl/_quoting_py.py -> build/lib.linux-aarch64-cpython-312/yarl
      copying yarl/_quoting.py -> build/lib.linux-aarch64-cpython-312/yarl
      running egg_info
      writing yarl.egg-info/PKG-INFO
      writing dependency_links to yarl.egg-info/dependency_links.txt
      writing requirements to yarl.egg-info/requires.txt
      writing top-level names to yarl.egg-info/top_level.txt
      reading manifest file 'yarl.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.cache' found anywhere in distribution
      warning: no previously-included files found matching 'yarl/*.html'
      warning: no previously-included files found matching 'yarl/*.so'
      warning: no previously-included files found matching 'yarl/*.pyd'
      no previously-included directories found matching 'docs/_build'
      adding license file 'LICENSE'
      writing manifest file 'yarl.egg-info/SOURCES.txt'
      copying yarl/__init__.pyi -> build/lib.linux-aarch64-cpython-312/yarl
      copying yarl/_quoting_c.pyi -> build/lib.linux-aarch64-cpython-312/yarl
      copying yarl/_quoting_c.pyx -> build/lib.linux-aarch64-cpython-312/yarl
      copying yarl/py.typed -> build/lib.linux-aarch64-cpython-312/yarl
      running build_ext
      building 'yarl._quoting_c' extension
      creating build/temp.linux-aarch64-cpython-312
      creating build/temp.linux-aarch64-cpython-312/yarl
      gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fPIC -I/usr/local/include/python3.12 -c yarl/_quoting_c.c -o build/temp.linux-aarch64-cpython-312/yarl/_quoting_c.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
Successfully built paho-mqtt
Failed to build aiohttp frozenlist multidict yarl
ERROR: Could not build wheels for aiohttp, frozenlist, multidict, yarl, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
pi@iDom-RaspberryPi4:~/GIT/comfoconnect-mqtt-bridge $

**Comment by michaelarnauts** [comment]
The Dockerfile should use a FROM python:3.11-slim or something. Not all dependencies have wheels available for Python 3.12.

**Comment by oysteing** [comment]
Thanks for reporting and the friendly hint on how to solve it. I have updated dependencies and recreated requirements.txt as well. Can you see if it works now?

**Comment by cyniu88** [comment]
now the docker image has been built correctly
