### ISSUE TITLE
bridge can not start 

### ISSUE THREAD

**Issue by cyniu88** [oysteing/comfoconnect-mqtt-bridge#3]
I built a docker image and started the service
(compose.ymal should be fixed   ':'  instad '=' )

i got flowing error:

The manual `connect` and `disconnect` methods are deprecated and will be removed in a future version. The preferred way to connect and disconnect the client is to use the context manager interface via `async with`. In case your use case needs to connect and disconnect manually, you can call the context manager's `__aenter__` and `__aexit__` methods as an escape hatch instead. `__aenter__` is equivalent to `connect`. `__aexit__` is equivalent to `disconnect` except that it forces disconnection instead of throwing an exception in case the client cannot disconnect cleanly. `__aexit__` expects three arguments: `exc_type`, `exc`, and `tb`. These arguments describe the exception that caused the context manager to exit, if any. You can pass `None` to all of these arguments in a manual call to `__aexit__`.

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "/app/comfobridge/__main__.py", line 63, in <module>

    asyncio.run(main())

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete

    return future.result()

  File "/app/comfobridge/__main__.py", line 57, in main

    await engine.start()

  File "/app/comfobridge/__main__.py", line 40, in start

    await self.ventilation.connect()

  File "/app/comfobridge/ventilation.py", line 18, in connect

    await self.comfoconnect.connect(self.local_uuid)

  File "/usr/local/lib/python3.10/site-packages/aiocomfoconnect/comfoconnect.py", line 68, in connect

    await self.cmd_start_session(True)

  File "/usr/local/lib/python3.10/site-packages/aiocomfoconnect/bridge.py", line 162, in _send

    self._writer.write(message.encode())

  File "/usr/local/lib/python3.10/site-packages/aiocomfoconnect/bridge.py", line 451, in encode

    return msg_len_buf + bytes.fromhex(self.src) + bytes.fromhex(self.dst) + cmd_len_buf + cmd_buf + msg_buf

ValueError: non-hexadecimal number found in fromhex() arg at position 1

>

**Comment by oysteing** [comment]
I don't get what's wrong with the environment variables. According to https://docs.docker.com/compose/compose-file/compose-file-v3/#environment, you can use either array or dictionary notation.

The warning at the start is a deprecation warning. The aiomqtt API must be used differently before moving to version 2.0.0. For now it should work.

I suspect one of your UUIDs are not hex formatted. Can you check your COMFOCONNECT_BRIDGE_UUID and COMFOCONNECT_LOCAL_UUID values?

**Comment by cyniu88** [comment]
here is my  compose.yaml

>
>version: '2'
>services:
>  comfobridge:
>    image: comfoconnect-mqtt-bridge
>    environment:
>      COMFOCONNECT_HOST: 192.168.13.121
>      COMFOCONNECT_BRIDGE_UUID: 00000000002b10148001144fd71e09c8
>     COMFOCONNECT_LOCAL_UUID: 00000000000000000000000000000001
 >     COMFOCONNECT_SENSORS: 221,274,275,276,290,291,292,294
>      COMFOBRIDGE_MIN_REPORTING_INTERVAL: 60
>      COMFOBRIDGE_MAX_REPORTING_INTERVAL: 3600
>      COMFOBRIDGE_MIN_REPORTING_CHANGE: 0.2
>      MQTT_HOST: 192.168.13.1
>      MQTT_CLIENT_ID: comfoconnect
>     MQTT_USER: comfoconnect
>      MQTT_PASSWORD: mypassword


it is ok, i guess 
PS I don't know how to paste yaml with indentation in lines

**Comment by oysteing** [comment]
I think the one value is being parsed as a number instead of a string. You should add quotes around the UUID values to be safe. I've updated the README accordingly.

**Comment by cyniu88** [comment]
after adding '' it started, but unfortunately I don't see any messages on mqtt and in container logs is only this 

> >
The manual `connect` and `disconnect` methods are deprecated and will be removed in a future version. The preferred way to connect and disconnect the client is to use the context manager interface via `async with`. In case your use case needs to connect and disconnect manually, you can call the context manager's `__aenter__` and `__aexit__` methods as an escape hatch instead. `__aenter__` is equivalent to `connect`. `__aexit__` is equivalent to `disconnect` except that it forces disconnection instead of throwing an exception in case the client cannot disconnect cleanly. `__aexit__` expects three arguments: `exc_type`, `exc`, and `tb`. These arguments describe the exception that caused the context manager to exit, if any. You can pass `None` to all of these arguments in a manual call to `__aexit__`.

      

      

no debuglogs or error logs

**Comment by oysteing** [comment]
I've tried ~10 different configurations with wrong settings, and they all output error messages/exceptions when the connection fails. Make sure you're also picking up stderr, not just stdout.

You should also be able to see the mqtt connection on the mqtt server. With mosquitto, it may look like this:
```
1707632564: New connection from 192.168.1.235:48383 on port 1883.
1707632564: New client connected from 192.168.1.235:48383 as comfoconnect (p2, c1, k60, u'comfoconnect').
```
or unauthorised:
```
1707632361: New connection from 192.168.1.235:60237 on port 1883.
1707632361: Client comfoconnect disconnected, not authorised.
```

I haven't built any debug logging into the bridge yet, but will have a look at that.

**Comment by oysteing** [comment]
I've added logging to the master branch. It defaults to log level INFO. Have a look at README.md to see how to enable DEBUG logging.

**Comment by oysteing** [comment]
Closing due to missing reporter response.
